name: GreenOps Live Demo 🚀
on:
  push:
    branches: [ main ]
  workflow_dispatch: # This line creates a clickable "Run" button for your jury demo!

jobs:
  simulate-build:
    runs-on: ubuntu-latest # This is the runner we analyze in our engine
    steps:
      - name: Compiling Assets
        run: echo "Simulating a build process..." && sleep 10
      - name: Running Tests
        run: echo "Running mock unit tests..." && sleep 5
      - name: Deploying App
        run: echo "Deployment complete!"
